<?php
/**
 * ZPay Payment Gateway
 *
 * @category ZPay
 * @package ZPay\Standard
 * @author Tiago Sampaio <tiago@tiagosampaio.com>
 * @link https://github.com/tiagosampaio
 * @link https://tiagosampaio.com
 *
 * Copyright (c) 2019.
 */
?>
<dl class="payment-method zpay_standard">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <?php if ($block->getInfo()->getAdditionalInformation()) : ?>
        <?php if ($block->getPayableTo()) : ?>
            <dd class="content">
                <strong><?= $block->escapeHtml(__('Make Check payable to')) ?></strong>
                <?= $block->escapeHtml($block->getPayableTo()) ?>
            </dd>
        <?php endif; ?>
        <?php if ($block->getMailingAddress()) : ?>
            <dd class="content">
                <strong><?= $block->escapeHtml(__('Send Check to')) ?></strong>
                <address class="checkmo mailing address">
                    <?= /* @noEscape */ nl2br($block->escapeHtml($block->getMailingAddress())) ?>
                </address>
            </dd>
        <?php endif; ?>
    <?php endif; ?>
</dl>
