<?php
/**
 * ZPay Payment Gateway
 *
 * @category ZPay
 * @package ZPay\Standard
 * @author Tiago Sampaio <tiago@tiagosampaio.com>
 * @link https://github.com/tiagosampaio
 * @link https://tiagosampaio.com
 *
 * Copyright (c) 2019.
 */

/**
 * @var \ZPay\Standard\Block\Payment\Wrapper $block
 * @var \Magento\Sales\Model\Order           $order
 */

if ($block->canDisplayWrapper()) :
    $order      = $block->getOrder();
    $orderId    = $order->getRealOrderId();
    $grandTotal = $order->getGrandTotal();

    $zOrderId   = $block->getZpayOrder()->getZpayOrderId();
    $zQuoteId   = $block->getZpayOrder()->getZpayQuoteId();
    $zAddress   = $block->getZpayOrder()->getZpayAddress();
    $zAmountTo  = $block->getZpayOrder()->getZpayAmountTo();
    $zTime      = $block->getZpayOrder()->getZpayTime();
    $zTimestamp = $block->convertDate($block->getZpayOrder()->getZpayTimestamp());
?>

<div class="zpay-wrapper">
    <h2><?php echo __('Please send Bitcoins to this address') ?></h2>
    <div class="code-wrapper">
        <div class="left">
            <canvas id="zpay-code" width="300" height="300"></canvas>
        </div>
        <div class="right">
            <div class="clock-div">
                <p class="clock-title"><?php echo __('This quote is available until...') ?></p>
                <span id="clock-timer"></span>
            </div>
            <button class="force-refresh"><?php echo __('Update Quote') ?></button>
        </div>
        <div class="loader"></div>
    </div>
    <table class="values">
        <tbody>
        <tr>
            <td><?php echo __('Address:') ?></td>
            <td><div class="code-text" data-total="<?php echo $zAddress ?>"><?php echo $zAddress ?></div></td>
        </tr>
        <tr>
            <td>R$:</td>
            <td><span class="brl"><?php echo $block->currency($order->getGrandTotal()) ?></span></td>
        </tr>
        <tr>
            <td>BTC:</td>
            <td><span class="btc"><?php echo number_format($zAmountTo, 8) ?></span></td>
        </tr>
        <tr>
            <td><?php echo __('BTC/BRL Rate:') ?></td>
            <td><span class="rate"><?php echo $block->currency($block->getBtcRate()) ?></span></td>
        </tr>
        </tbody>
    </table>

<!--    <script type="text/x-magento-init">{".force-refresh":{"ZPay_Standard/js/standard/test":{"url":"http://www.example.url", "method":"post"}}}</script>-->

    <script type="text/javascript">
        requirejs(['jquery', 'zpay-payment'], function (jQuery, ZPay) {
            ZPay.setup(
                jQuery('#zpay-code'),
                jQuery('.force-refresh'),
                '<?php echo $block->dataHelper()->getUpdateUrl() ?>',
                '<?php echo $block->dataHelper()->getVerifyUrl() ?>',
                '<?php echo $block->dataHelper()->getVerifiedUrl() ?>',
                10000,
                function (api) {
                    jQuery('.code-text').text(api.ZOrder.address);
                    jQuery('.btc').text(api.ZOrder.amount);
                }
            ).setupZOrder(
                '<?php echo $zOrderId ?>',
                '<?php echo $zQuoteId ?>',
                '<?php echo $zAddress?>',
                '<?php echo $zAmountTo?>',
                '<?php echo $zTime?>',
                '<?php echo $zTimestamp?>'
            ).setTimerContainer(jQuery('#clock-timer'))
                .start();
        });
    </script>
</div>
<?php endif; ?>