<?php

// @codingStandardsIgnoreFile

?>

<style type="text/css">
    .validate-success,
    .validate-failure {
        padding: 5px;
    }

    .validate-success {
        color: green;
    }

    .validate-failure {
        color: red;
    }
</style>

<?php /* @var $block \ZPay\Standard\Block\System\Config\Credentials\ValidateCredentials */ ?>
<script type="application/javascript">
    require([
        'jquery',
        'prototype',
        'mage/backend/validation',
        'jquery/validate'
    ], function($){
        let container        = $('#validate_span');
        let messageContainer = $('#validate_message_span');
        let loader           = $('#validate_loader');

        function startRequest() {
            if (container.hasClass('no-display')) {
                container.removeClass('no-display');
            }
            
            if (loader.hasClass('no-display')) {
                loader.removeClass('no-display');
            }

            messageContainer.text('');
        }

        function endRequest() {
            if (!container.hasClass('no-display')) {
                container.addClass('no-display');
            }

            if (!loader.hasClass('no-display')) {
                loader.addClass('no-display');
            }

            messageContainer.removeClass('validate-success');
            messageContainer.removeClass('validate-failure');
            messageContainer.text('');
        }

        $('#validate_credentials').click(function () {
            var params = {
                environment : $('#payment_us_zpay_standard_environment').val(),
                username    : $('#payment_us_zpay_standard_username').val(),
                password    : $('#payment_us_zpay_standard_password').val(),
                contract_id : $('#payment_us_zpay_standard_contract_id').val(),
                form_key    : '<?= $block->getFormKey() ?>'
            };

            new $.ajax('<?= $block->getAjaxValidateUrl() ?>', {
                data: params,
                beforeSend: function () {
                    startRequest();
                },
                success: function (transport) {
                    if (transport.success) {
                        messageContainer.addClass('validate-success');
                    } else {
                        messageContainer.addClass('validate-failure');
                    }

                    messageContainer.text(transport.message);
                },
                error: function (transport) {

                },
                complete: function (transport) {
                    loader.addClass('no-display');
                    setTimeout(endRequest, 2000);
                }
            });
        });
    });
</script>

<?php echo $block->getButtonHtml() ?>
<span class="validator-indicator no-display" id="validate_span">
    <img id="validate_loader" class="no-display" alt="Validating" style="margin:0 5px" src="<?= $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <span id="validate_message_span"></span>
</span>
<!--<input type="hidden" id="synchronize-validation-input" class="required-synchronize no-display"/>-->
