<?php
/**
 * ZPay Payment Gateway
 *
 * @category ZPay
 * @package ZPay\Standard
 * @author Tiago Sampaio <tiago@tiagosampaio.com>
 * @link https://github.com/tiagosampaio
 * @link https://tiagosampaio.com
 *
 * Copyright (c) 2019.
 */

/** @var \ZPay\Standard\Block\Info\Standard $block */
?>
<h4><?php echo __('Paid with BitCoins using ZPay') ?></h4>

<p><?php echo __('Reference ID: %1', $block->getZPayOrder()->getZpayOrderId())?></p>
<p><?php echo __('Address: %1', $block->getZPayOrder()->getZpayAddress())?></p>
<p><?php echo __('BTC: %1', number_format((float) $block->getZPayOrder()->getZpayAmountTo(), 8))?></p>
